/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.37
 * Generated at: 2016-10-27 15:36:26 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class register_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<html>\r\n");
      out.write("<body>\r\n");
      out.write("\t\t<div id=\"register\" class=\"animate form\">\r\n");
      out.write("\t\t\t<form  action=\"registerhere\" autocomplete=\"on\"> \r\n");
      out.write("\t\t\t\t<h1> Sign up </h1> \r\n");
      out.write("\t\t\t\t<table align:center>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<td><label for=\"First Namesignup\" class=\"Fname\" data-icon=\"F\">First Name</label></td>\r\n");
      out.write("\t\t\t\t\t<td>:</td>\r\n");
      out.write("\t\t\t\t\t<td><input id=\"First Namesignup\" name=\"First Namesignup\" required=\"required\" type=\"text\" placeholder=\"mysuperFirstname\" /></td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t \t<tr>\r\n");
      out.write("\t\t\t\t\t<td><label for=\"Last Namesignup\" class=\"Lname\" data-icon=\"L\">Last Name</label>\r\n");
      out.write("\t\t\t\t\t<td>:</td>\r\n");
      out.write("\t\t\t\t\t<td><input id=\"Last Namesignup\" name=\"Last Namesignup\" required=\"required\" type=\"text\" placeholder=\"mysuperLastname\" />\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\r\n");
      out.write("                   \t<tr>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<td><label for=\"DOBsignup\" class=\"Lname\" data-icon=\"L\">DOB</label></td>\r\n");
      out.write("\t\t\t\t\t<td>:</td>\r\n");
      out.write("\t\t\t\t\t<td><input id=\"DOBsignup\" name=\"DOBsignup\" required=\"required\" type=\"text\" placeholder=\"dd - mm - yy\" /></td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t \r\n");
      out.write("\t\t\t\t\t<td><label for=\"usernamesignup\" class=\"uname\" data-icon=\"u\">Your username</label></td>\r\n");
      out.write("\t\t\t\t\t<td>:</td>\r\n");
      out.write("\t\t\t\t\t<td><input id=\"usernamesignup\" name=\"usernamesignup\" required=\"required\" type=\"text\" placeholder=\"mysuperusername690\" /></td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t \r\n");
      out.write("\t\t\t\t\t<td><label for=\"emailsignup\" class=\"youmail\" data-icon=\"e\" > Your email</label></td>\r\n");
      out.write("\t\t\t\t\t<td>:</td>\r\n");
      out.write("\t\t\t\t\t<td><input id=\"emailsignup\" name=\"emailsignup\" required=\"required\" type=\"email\" placeholder=\"mysupermail@mail.com\"/> </td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<tr>\t\t\t\r\n");
      out.write("\t\t\t\t \r\n");
      out.write("\t\t\t\t\t<td><label for=\"passwordsignup\" class=\"youpasswd\" data-icon=\"p\">Your password </label></td>\r\n");
      out.write("\t\t\t\t\t<td>:</td>\r\n");
      out.write("\t\t\t\t\t<td><input id=\"passwordsignup\" name=\"passwordsignup\" required=\"required\" type=\"password\" placeholder=\"eg. X8df!90EO\"/></td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t \r\n");
      out.write("\t\t\t\t\t<td><label for=\"passwordsignup_confirm\" class=\"youpasswd\" data-icon=\"p\">Please confirm your password </label></td>\r\n");
      out.write("\t\t\t\t\t<td>:</td>\r\n");
      out.write("\t\t\t\t\t<td><input id=\"passwordsignup_confirm\" name=\"passwordsignup_confirm\" required=\"required\" type=\"password\" placeholder=\"eg. X8df!90EO\"/></td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t \r\n");
      out.write("\t\t\t\t\t<td><label for=\"Address1signup\" class=\"Address1\" data-icon=\"A1\">Address1</label></td>\r\n");
      out.write("\t\t\t\t\t<td>:</td>\r\n");
      out.write("\t\t\t\t\t<td><input id=\"Address1signup\" name=\"Address1signup\" required=\"required\" type=\"text\" placeholder=\"Address1\" /></td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t \r\n");
      out.write("\t\t\t\t\t<td><label for=\"Address2signup\" class=\"Address2\" data-icon=\"A1\">Address2</label></td>\r\n");
      out.write("\t\t\t\t\t<td>:</td>\r\n");
      out.write("\t\t\t\t\t<td><input id=\"Address2signup\" name=\"Address2signup\" required=\"required\" type=\"text\" placeholder=\"Address2\" /></td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write(" \r\n");
      out.write("\t\t\t\t\t<td><label for=\"Pincodesignup\" class=\"Pincode\" data-icon=\"A1\">Pincode</label></td>\r\n");
      out.write("\t\t\t\t\t<td>:</td>\r\n");
      out.write("\t\t\t\t\t<td><input id=\"Pincodesignup\" name=\"Pincodesignup\" required=\"required\" type=\"text\" placeholder=\"Enter Pincode\" /></td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<td> State</td><td>:</td> <td><Select>\r\n");
      out.write("\t\t\t\t<option value=\"TamilNadu\">TamilNadu</option>\r\n");
      out.write("\t\t\t\t<option value=\"Kerala\">Kerala</option>\r\n");
      out.write("\t\t\t\t<option value=\"Karnataka\">Karnataka</option>\r\n");
      out.write("\t\t\t\t<option value=\"AndhraPradesh\">AndhraPradesh</option></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("<tr>\r\n");
      out.write("\t\t\t\t<td><p class=\"signin button\"> \r\n");
      out.write("\t\t\t\t\t<input type=\"submit\" value=\"Sign up\"/> \r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("<tr>\r\n");
      out.write("\t\t\t\t<td> <p class=\"#tologin\"> \r\n");
      out.write("\t\t\t\t \r\n");
      out.write("\t\t\t\t\tAlready a member ?\r\n");
      out.write("\t\t\t\t\t<a href=\"login\" class=\"to_register\"> Go and log in </a></td>\r\n");
      out.write("</tr></Table>\r\n");
      out.write("</form>\r\n");
      out.write("</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
